-- FESTIO 3차 고도화: 결제 및 주문 시스템 Supabase 이전 테이블 구조 설계

-- 1. 장바구니 테이블 (기존 로컬스토리지 대체)
DROP TABLE IF EXISTS public.shop_cart CASCADE;

CREATE TABLE public.shop_cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email TEXT NOT NULL,
    product_id UUID NOT NULL REFERENCES public.shop_products(id) ON DELETE CASCADE,
    qty INTEGER NOT NULL DEFAULT 1,
    options JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 결제 주문 테이블 (기존 Java Backend 대체)
DROP TABLE IF EXISTS public.shop_orders CASCADE;

CREATE TABLE public.shop_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL, -- 예: F12345678901
    user_email TEXT NOT NULL,
    user_name TEXT,
    user_phone TEXT,
    total_price INTEGER NOT NULL,
    discount_amount INTEGER DEFAULT 0,
    final_price INTEGER NOT NULL,
    payment_method TEXT NOT NULL, -- 'festiopay', 'card', 'toss'
    status TEXT NOT NULL DEFAULT 'PENDING', -- PENDING, PREPARING, READY, COMPLETED, CANCELLED
    secret_key TEXT, -- 오프라인 QR 검증용 TOTP Secret
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. 결제 주문 상세 상품 테이블
DROP TABLE IF EXISTS public.shop_order_items CASCADE;

CREATE TABLE public.shop_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.shop_orders(id) ON DELETE CASCADE,
    store_id UUID,
    store_name TEXT,
    product_id UUID REFERENCES public.shop_products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    qty INTEGER NOT NULL,
    unit_price INTEGER NOT NULL,
    options JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 추가 (조회 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_shop_orders_user_email ON public.shop_orders(user_email);
CREATE INDEX IF NOT EXISTS idx_shop_order_items_order_id ON public.shop_order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_shop_order_items_store_name ON public.shop_order_items(store_name);

-- 필요 시 RLS (Row Level Security) 설정
-- ALTER TABLE public.shop_orders ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Users can view their own orders" ON public.shop_orders FOR SELECT USING (user_email = auth.jwt()->>'email');
