-- ==============================================================================
-- [FESTIO] Supabase 초기 데이터베이스 스키마 및 샘플 데이터 설정 스크립트
-- 이 스크립트를 Supabase 대시보드의 'SQL Editor'에 복사하여 실행해주세요.
-- ==============================================================================


-- 1. 사용자(app_user) 테이블 생성
CREATE TABLE IF NOT EXISTS public.app_user (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  name text,
  phone text,
  email text,
  role text DEFAULT 'USER',
  is_email_agreed boolean DEFAULT false,
  is_face_registered boolean DEFAULT false,
  face_landmark_data jsonb,
  created_at timestamp with time zone DEFAULT now()
);

-- 2. 행사(festival) 테이블 생성
CREATE TABLE IF NOT EXISTS public.festival (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  start_date date,
  end_date date,
  category text,
  venue text,
  start_time time,
  end_time time,
  min_price integer DEFAULT 0,
  is_active boolean DEFAULT true,
  is_adult_only boolean DEFAULT false,
  thumbnail_url text,
  map_image_url text,
  badge_label text,
  is_hot boolean DEFAULT false,
  view_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- 3. 쿠폰(coupon) 테이블 생성
CREATE TABLE IF NOT EXISTS public.coupon (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  discount_type text, -- 'PERCENT' or 'AMOUNT'
  discount_value integer,
  min_order_amount integer DEFAULT 0,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);

-- 4. 구역(festival_zone) 테이블 생성
CREATE TABLE IF NOT EXISTS public.festival_zone (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  festival_id bigint REFERENCES public.festival(id) ON DELETE CASCADE,
  zone_name text,
  zone_code text,
  capacity integer,
  remaining integer,
  price integer,
  color_code text
);

-- 5. 예매/주문(orders) 테이블 생성
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.app_user(id),
  festival_id bigint REFERENCES public.festival(id),
  zone_id bigint REFERENCES public.festival_zone(id),
  quantity integer,
  total_amount integer,
  status text DEFAULT 'PENDING',
  payment_method text,
  pg_provider text,
  order_uid text,
  created_at timestamp with time zone DEFAULT now()
);

-- 6. 사용자 쿠폰 보유(user_coupon) 테이블 생성
CREATE TABLE IF NOT EXISTS public.user_coupon (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.app_user(id),
  coupon_id bigint REFERENCES public.coupon(id),
  is_used boolean DEFAULT false,
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);

-- 7. 찜 목록(wishlist) 테이블 생성
CREATE TABLE IF NOT EXISTS public.wishlist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.app_user(id),
  event_no bigint REFERENCES public.festival(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(user_id, event_no)
);

-- ==============================================================================
-- 접근 권한 (RLS - Row Level Security) 정책 설정
-- ==============================================================================
ALTER TABLE public.app_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.festival ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.festival_zone ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_coupon ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;

-- festival, coupon, festival_zone: 모든 사용자가 읽기 가능
CREATE POLICY "Enable read access for all users" ON public.festival FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON public.coupon FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON public.festival_zone FOR SELECT USING (true);

-- app_user, orders, user_coupon, wishlist: 로그인한 본인만 조회/수정 가능
CREATE POLICY "Users can view own data" ON public.app_user FOR SELECT USING (auth.uid()::text = id::text);
CREATE POLICY "Users can update own data" ON public.app_user FOR UPDATE USING (auth.uid()::text = id::text);

CREATE POLICY "Users can view own orders" ON public.orders FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can view own coupons" ON public.user_coupon FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Users can view own wishlist" ON public.wishlist FOR SELECT USING (auth.uid()::text = user_id::text);
CREATE POLICY "Users can insert own wishlist" ON public.wishlist FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);
CREATE POLICY "Users can delete own wishlist" ON public.wishlist FOR DELETE USING (auth.uid()::text = user_id::text);

-- 완료 메시지
-- 실행 후 API와 연동이 가능합니다.
